org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

minecraft_version=1.21.1
neo_version=21.1.244
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
cobblemon_project=MdwFAVRL
cobblemon_version=7otgw3aH
kotlinforforge_project=ordsPcFz
kotlinforforge_version=uhJhCT7X

mod_id=entitybattle
mod_version=0.2.0-beta.1
mod_group_id=dev.entitybattle
